theme: jekyll-theme-minimal
title: Corda Network Foundation
description: Corda Network is the internet of Corda nodes, governed by an open Foundation.
logo: https://avatars3.githubusercontent.com/u/22600631?s=100